name: VisualSkyrim
description: Blogging about code and fun
meta_description: "VisualSkyrim, Blogging about codes and fun"

markdown: redcarpet
pygments: true
logo: true
paginate: 15

# Details for the RSS feed generator
url:            'VisualSkyrim.github.io'
author:         'Chris Kong'
